# Generated by Django 3.1.3 on 2021-05-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210517_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbNail',
            new_name='thumbnail',
        ),
    ]
